version: '3'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 3002

  nginx:
    container_name: nginx
    image: nginx:1.22
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge